###

GET http://localhost:8080/message

###

GET http://localhost:8080/message/1

###

POST http://localhost:8080/message
Content-Type: application/json

{
  "text": "message"
}

###

PUT http://localhost:8080/message/2
Content-Type: application/json

{
  "text": "new text"
}

###

DELETE http://localhost:8080/message/2

###
